ira="class:avaamo__icon"
getstarted="class:get-started-link"
switchtotype="xpath://div[@title='Switch to typing']"
welcomemessage="class:welcome-message"
message="xpath://p[@class='desc text-content '][contains(.,'Hi there, what can I')]"
menu_button_open="xpath://div[contains(@title,'Switch to bot menu')]"
start_over="//a[@class='botMenu__menu__item'][contains(.,'Start Over')]"
download_motor_policy="xpath://div[contains(.,'Download Motor Policy')]"
download_link = "xpath://a[contains(@type,'web_page')]"
selectframe="name:avaamoIframe"
input_text="xpath://textarea[contains(@dir,'auto')]"
click_send_button="xpath://div[@class='ptr locale-trans send enabled'][contains(.,'Send')]"
first_name="xpath://input[@class='textbox'][contains(@id,'f09235')]"
address="xpath://textarea[@class='textbox'][contains(@id,'fe5134')]"
gender="xpath://label[contains(.,'Male')]"
search_box="xpath://input[@placeholder='Select']"
veryoftern="xpath://li[@class='item'][contains(.,'Very Often')]"
rate="xpath://label[contains(.,'5')]"
Click_submit="xpath://button[@type='button'][contains(.,'Submit')]"
clickgoogle="xpath://a[contains(.,'Google')]"
closegoogle="xpath://button[@type='button'][contains(.,'×')]"
call="xpath://a[contains(.,'Call')]"
yes="xpath://a[contains(@title,'Yes')]"